# Generated by Django 3.2 on 2021-12-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('detail', models.TextField()),
                ('precaution', models.TextField()),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('next_visit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
