# Generated by Django 3.2 on 2021-12-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='next_visit_date',
            field=models.DateTimeField(),
        ),
    ]
